# -*- coding: utf-8 -*-
"""PLOTS_Muñoz_Escobar_Daniel_Arukin_S9C1_EDP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12QvBIP54vGlCl8rGJuXDDFaPTfv_n9nt
"""

import numpy as np
import matplotlib.pylab as plt

#Difusión 2D

#t=0
datos_t0=np.genfromtxt("Placa de calor, t=0",dtype=float,delimiter=',')

plt.figure()
plt.title('Placa de calor, t=0', fontsize=12)
plt.imshow(datos_t0,cmap=None)
plt.savefig("Placa de calor, t=0.pdf")

#t=100
datos_t100=np.genfromtxt("Placa de calor, t=100",dtype=float,delimiter=',')

plt.figure()
plt.title('Placa de calor, t=100', fontsize=12)
plt.imshow(datos_t100,cmap=None)
plt.savefig("Placa de calor, t=100.pdf")

#t=1000
datos_t1000=np.genfromtxt("Placa de calor, t=1000",dtype=float,delimiter=',')

plt.figure()
plt.title('Placa de calor, t=1000', fontsize=12)
plt.imshow(datos_t1000,cmap=None)
plt.savefig("Placa de calor, t=1000.pdf")

#t=2500
datos_t2500=np.genfromtxt("Placa de calor, t=2500",dtype=float,delimiter=',')

plt.figure()
plt.title('Placa de calor, t=2500', fontsize=12)
plt.imshow(datos_t2500,cmap=None)
plt.savefig("Placa de calor, t=2500.pdf")